<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-FTE0JVJ" name="testRunner.simulator" tests="24" failures="3" timestamp="2022-12-11T19:52:24 EET" time="455.246" errors="0">
  <testcase name="runScenario" time="24.241" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="24.622" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="20.949" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="13.369" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="18.595" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="22.918" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="20.505" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="13.547" classname="testRunner.simulator">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/new-online-store-is-open] but found [https://demo.nopcommerce.com/news/rss/1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefs.followUsFeatureSteps.checkOnUrl(followUsFeatureSteps.java:34)
at ✽.user should go to selected "https://demo.nopcommerce.com/new-online-store-is-open"(file:///C:/Users/user/IdeaProjects/E-commerce%20App%20Automation%20Testing/src/main/resources/features/followUs.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="12.465" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="12.763" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="74.553" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="12.155" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="15.001" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="14.934" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="8.827" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="15.973" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="9.782" classname="testRunner.simulator">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefs.sliderFeatureSteps.checkOnNokiaUrl(sliderFeatureSteps.java:27)
at ✽.user should navigate to Nokia page(file:///C:/Users/user/IdeaProjects/E-commerce%20App%20Automation%20Testing/src/main/resources/features/slider.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="13.988" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="23.460" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="21.655" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="16.599" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="9.101" classname="testRunner.simulator">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefs.sliderFeatureSteps.checkOnIphoneUrl(sliderFeatureSteps.java:37)
at ✽.user should navigate to iphone page(file:///C:/Users/user/IdeaProjects/E-commerce%20App%20Automation%20Testing/src/main/resources/features/slider.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="15.050" classname="testRunner.simulator"/>
  <system-out/>
  <testcase name="runScenario" time="20.194" classname="testRunner.simulator"/>
  <system-out/>
</testsuite> <!-- testRunner.simulator -->
